name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install API deps
        working-directory: api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Quick API import check
        working-directory: api
        run: |
          python - <<'PY'
          import importlib
          import sys
          try:
              importlib.import_module('fastapi')
              importlib.import_module('httpx')
              print('FastAPI and httpx import OK')
          except Exception as e:
              print('Import failed:', e)
              sys.exit(1)
          PY

      - name: Build API image
        run: docker build -t heypico-api ./api

      - name: Build Web image
        run: docker build -t heypico-web ./web
